"""Make the three daily exports the pipeline loads, in data/raw/.

    sales.csv   date, store, item, units_sold                 daily sales per store and item
    stock.csv   date, store, item, units_received, on_hand, on_order
                                                              end-of-day stock (GENERATED)
    item.csv    item, unit_cost                               cost of one unit (GENERATED)

Demand is the public Store Item Demand Forecasting file (10 stores x 50 items, every day of
2013 to 2017), downloaded once from a pinned GitHub copy. The stock is generated by replaying
how the stores order today, by hand:

    Every Monday morning each store counts its shelves and tops every item back up to the same
    shelf level: three weeks of the store's average item sales, whatever the item sells. The
    supplier delivers 4 days later. The average is the store's sales in the year before (2013
    uses its own year).

A shelf can only sell what it holds, so units_sold = min(demand, stock on the shelf).

Run once from the repo root:  python data/make_data.py
"""
import hashlib
import urllib.request
from pathlib import Path

import numpy as np
import pandas as pd

RAW = Path(__file__).parent / "raw"
DEMAND_URL = ("https://raw.githubusercontent.com/allmeidaapedro/Store-Item-Demand-Forecasting/"
              "5bb476c91b4bdf2e3c9934b442765b83b4d62d45/input/train.csv")
DEMAND_SHA256 = "038f25690a65149c94f86ddd3deceda20c037a5cfd754cafdfc539a72992f2ed"
LEAD_DAYS = 4

RAW.mkdir(exist_ok=True)
demand_file = RAW / "store_item_demand.csv"
if not demand_file.exists():
    print("Downloading", DEMAND_URL)
    urllib.request.urlretrieve(DEMAND_URL, demand_file)
digest = hashlib.sha256(demand_file.read_bytes()).hexdigest()
assert digest == DEMAND_SHA256, f"{demand_file} changed: sha256 {digest}"

demand = pd.read_csv(demand_file, parse_dates=["date"])
assert len(demand) == 913_000 and demand["sales"].min() >= 0

# One row per day, one column per (store, item).
wide = demand.pivot_table(index="date", columns=["store", "item"], values="sales")
days, cols = wide.index, wide.columns
want = wide.to_numpy()
stores = cols.get_level_values("store").to_numpy()

# The habit's shelf level per store and year: three weeks of the average item's sales.
avg = demand.groupby(["store", demand["date"].dt.year])["sales"].mean()
def shelf_level(year):
    source = max(year - 1, 2013)
    return np.round(21 * np.array([avg[(s, source)] for s in stores]))

on_hand = shelf_level(2013)
arrivals = np.zeros((len(days) + LEAD_DAYS, len(cols)))
sold = np.zeros_like(want)
received = np.zeros_like(want)
end_stock = np.zeros_like(want)
on_order = np.zeros_like(want)

for t, day in enumerate(days):
    if day.dayofweek == 0:  # Monday count, before the shop opens
        arrivals[t + LEAD_DAYS] += np.maximum(shelf_level(day.year) - on_hand, 0)
    received[t] = arrivals[t]
    on_hand = on_hand + arrivals[t]
    sold[t] = np.minimum(want[t], on_hand)
    on_hand = on_hand - sold[t]
    end_stock[t] = on_hand
    on_order[t] = arrivals[t + 1:t + LEAD_DAYS + 1].sum(axis=0)  # ordered, not delivered yet

def long(values, name):
    frame = pd.DataFrame(values, index=days, columns=cols).stack(["store", "item"], future_stack=True)
    return frame.rename(name).astype(int)

sales = long(sold, "units_sold").reset_index()
stock = pd.concat([long(received, "units_received"), long(end_stock, "on_hand"), long(on_order, "on_order")],
                  axis=1).reset_index()
assert len(sales) == len(stock) == 913_000 and (stock["on_hand"] >= 0).all()

rng = np.random.default_rng(4)
items = pd.DataFrame({"item": range(1, 51), "unit_cost": rng.uniform(1, 30, 50).round(2)})

sales.to_csv(RAW / "sales.csv", index=False, date_format="%Y-%m-%d")
stock.to_csv(RAW / "stock.csv", index=False, date_format="%Y-%m-%d")
items.to_csv(RAW / "item.csv", index=False)
print(f"{len(sales):,} sales rows, {len(stock):,} stock rows, {len(items)} items -> {RAW}")
